import type { SceneProfile } from "./types";

const sharedNegatives = ["readable text, letters, numbers, typography, logo, watermark", "fake product, package, bottle, label or branded container", "collage, poster, border or UI screenshot", "busy objects inside reserved product and text zones", "transparent background, alpha channel, cutout, isolated object, black void or missing pixels"];

export const sceneProfiles: SceneProfile[] = [
  {
    id: "personal-care-cooling-impact",
    label: "쿨링 임팩트",
    categoryMatchers: ["바디워시", "샤워젤", "퍼스널케어", "생활용품"],
    benefitMatchers: ["쿨링", "민트", "시원", "여름", "상쾌"],
    visualMood: ["electric cooling", "bold", "energetic", "refreshing"],
    environment: ["abstract cold-water stage", "deep cyan atmospheric depth"],
    props: ["water arcs", "ice-like translucent forms", "mint leaves used sparingly"],
    lighting: ["cool backlight", "cyan rim light", "crisp specular highlights"],
    textures: ["water", "condensation", "frosted acrylic"],
    colorHints: ["#02e4c2", "#00a8e8", "#07151f", "#ffffff"],
    compositionRules: ["reserve upper-left for giant hook", "keep center-right quiet for real product", "build motion around, never through, the product safe zone"],
    productSafeZoneRules: ["center-right 42% x 62%", "ground plane visible below product"],
    textSafeZoneRules: ["upper-left 52% x 30% with dark calm contrast", "bottom strip 100% x 12%"],
    negativePromptRules: [...sharedNegatives, "no generated cosmetic bottle", "no frozen food or snow landscape"],
    compatibleArchetypes: ["giant-hook", "numeric-proof", "product-hero", "problem-solution"],
  },
  {
    id: "personal-care-shower-freshness",
    label: "샤워 후 상쾌함",
    categoryMatchers: ["바디워시", "샤워젤", "퍼스널케어"],
    benefitMatchers: ["샤워", "향", "깨끗", "상쾌", "체취"],
    visualMood: ["fresh shower", "clean", "sensory", "modern"],
    environment: ["contemporary shower room", "soft wet glass depth"],
    props: ["water droplets", "subtle steam", "folded neutral towel"],
    lighting: ["soft window light", "cool bathroom bounce", "gentle rim light"],
    textures: ["wet tile", "glass", "mist"],
    colorHints: ["#bff7ee", "#1d827d", "#f6fbfa", "#162729"],
    compositionRules: ["leave one side uncluttered for product", "keep people out of the product safe zone", "use shallow depth"],
    productSafeZoneRules: ["right-center 38% x 58%"],
    textSafeZoneRules: ["upper-left 52% x 32% with low-detail wall"],
    negativePromptRules: [...sharedNegatives, "no generated person holding a fake product", "no clinical lab"],
    compatibleArchetypes: ["problem-solution", "lifestyle-context", "product-hero"],
  },
  {
    id: "personal-care-post-workout",
    label: "운동 후 샤워",
    categoryMatchers: ["바디워시", "퍼스널케어", "생활용품"],
    benefitMatchers: ["운동", "땀", "체취", "쿨링", "멘스"],
    visualMood: ["active", "urban", "fresh after exertion", "confident"],
    environment: ["modern gym-to-shower transition", "dark locker room depth"],
    props: ["towel", "water droplets", "subtle sports bag silhouette"],
    lighting: ["cool overhead strip light", "teal rim light", "controlled contrast"],
    textures: ["matte locker", "wet glass", "rubber floor"],
    colorHints: ["#00d8b4", "#15232a", "#ecfffb"],
    compositionRules: ["context remains secondary", "right-center product focus", "left text column stays calm"],
    productSafeZoneRules: ["right-center 40% x 60%"],
    textSafeZoneRules: ["left 48% x 50% with dark scrim-ready field"],
    negativePromptRules: [...sharedNegatives, "no identifiable athlete endorsement", "no body transformation"],
    compatibleArchetypes: ["problem-solution", "lifestyle-context", "giant-hook"],
  },
  {
    id: "personal-care-clean-product",
    label: "클린 제품 히어로",
    categoryMatchers: ["뷰티", "화장품", "퍼스널케어", "생활용품"],
    benefitMatchers: ["클린", "신상", "향", "선물", "프리미엄"],
    visualMood: ["clean commerce", "polished", "bright", "brand-led"],
    environment: ["minimal studio set with depth", "soft colored acrylic planes"],
    props: ["subtle ingredient cues", "translucent pedestal", "soft reflective floor"],
    lighting: ["large softbox", "controlled rim light", "clean contact shadow"],
    textures: ["acrylic", "water gloss", "soft matte wall"],
    colorHints: ["#ecfffa", "#61d9c8", "#ffffff", "#132724"],
    compositionRules: ["top-left text field", "center-right product pedestal", "few props only"],
    productSafeZoneRules: ["center-right 40% x 62%"],
    textSafeZoneRules: ["upper-left 50% x 36% high contrast"],
    negativePromptRules: [...sharedNegatives, "no generated package", "no excessive flowers"],
    compatibleArchetypes: ["product-hero", "three-benefits", "premium-product"],
  },
  {
    id: "food-meat-grill",
    label: "육즙 그릴",
    categoryMatchers: ["고기", "육류", "한우", "축산", "식품"],
    benefitMatchers: ["육즙", "구이", "부드러움", "갈비", "등심", "살치살"],
    visualMood: ["appetizing", "high-energy grill", "warm", "premium value"],
    environment: ["clean dark grill stage", "restaurant grill depth"],
    props: ["clean unoccupied grill surface", "light steam at the far edge", "wood or black stone edge"],
    lighting: ["warm side light", "controlled amber fire glow", "clean food highlights"],
    textures: ["grill metal", "dark stone", "warm wood"],
    colorHints: ["#160f0b", "#d62b1f", "#ffcf29", "#fff5e8"],
    compositionRules: ["keep every food and sold-category object out of the entire frame", "reserve top for headline", "provide dark grounding behind the later real meat image"],
    productSafeZoneRules: ["center or center-right 56% x 55%", "clear contact surface"],
    textSafeZoneRules: ["top 100% x 25%", "bottom 100% x 18% for price/footer"],
    negativePromptRules: [...sharedNegatives, "no raw or cooked meat anywhere", "no steak, barbecue, food plate or edible object", "no dirty grill", "no burnt black food", "no hands obscuring safe zone"],
    compatibleArchetypes: ["price-event", "product-hero", "giant-hook", "numeric-proof"],
  },
  {
    id: "food-meat-camping",
    label: "캠핑 그릴",
    categoryMatchers: ["고기", "육류", "한우", "식품"],
    benefitMatchers: ["캠핑", "모임", "푸짐", "구성", "가족"],
    visualMood: ["outdoor gathering", "warm", "generous", "weekend appetite"],
    environment: ["tasteful campsite table at dusk", "portable grill context"],
    props: ["wood table", "camp lantern bokeh", "clean grill tools"],
    lighting: ["golden-hour ambient", "warm lantern rim", "soft foreground fill"],
    textures: ["wood", "canvas", "metal grill"],
    colorHints: ["#23170f", "#c77b32", "#f2c14e", "#f8eee1"],
    compositionRules: ["do not identify a real location", "reserve foreground for real product", "people only as soft silhouettes"],
    productSafeZoneRules: ["lower-center 58% x 48%"],
    textSafeZoneRules: ["upper-left 55% x 30% with dark tent or sky field"],
    negativePromptRules: [...sharedNegatives, "no raw or cooked meat anywhere", "no fake meat portion, steak, food plate or edible object", "no crowded people", "no unsafe flame"],
    compatibleArchetypes: ["seasonal-context", "lifestyle-context", "price-event"],
  },
  {
    id: "food-meat-family-meal",
    label: "가족 식탁",
    categoryMatchers: ["고기", "육류", "한우", "식품", "선물"],
    benefitMatchers: ["가족", "식탁", "외식", "모임", "선물"],
    visualMood: ["warm family table", "abundant", "trustworthy", "inviting"],
    environment: ["clean Korean dining table", "warm home dining room"],
    props: ["empty neutral tableware", "folded linen napkin", "subtle empty serving board"],
    lighting: ["warm window light", "soft overhead fill", "natural food highlights"],
    textures: ["wood table", "linen", "ceramic"],
    colorHints: ["#3a2418", "#b94a32", "#f4dfbd", "#fffaf2"],
    compositionRules: ["table remains secondary", "leave hero opening in lower center", "no identifiable family faces"],
    productSafeZoneRules: ["lower-center 54% x 46%"],
    textSafeZoneRules: ["upper 100% x 27% calm wall/background"],
    negativePromptRules: [...sharedNegatives, "no raw or cooked meat anywhere", "no fake meat plate, side dish, food serving or edible object", "no messy table"],
    compatibleArchetypes: ["problem-solution", "lifestyle-context", "three-benefits"],
  },
  {
    id: "food-meat-premium-table",
    label: "프리미엄 테이블",
    categoryMatchers: ["고기", "육류", "한우", "식품", "선물"],
    benefitMatchers: ["프리미엄", "선물", "마블링", "품질", "등급"],
    visualMood: ["premium food", "restrained", "rich", "gift-worthy"],
    environment: ["dark stone dining surface", "premium butcher-table atmosphere without signage"],
    props: ["walnut board", "dark linen", "subtle brass accent"],
    lighting: ["directional warm key", "soft shadow", "controlled rim light"],
    textures: ["stone", "walnut", "linen"],
    colorHints: ["#14100e", "#8f5d3b", "#d6a84f", "#f6efe8"],
    compositionRules: ["few props", "large clean product stage", "left text column"],
    productSafeZoneRules: ["center-right 50% x 58%"],
    textSafeZoneRules: ["upper-left 46% x 38% dark contrast"],
    negativePromptRules: [...sharedNegatives, "no raw or cooked meat anywhere", "no invented certification", "no fake luxury logo", "no fake meat cut, steak, food plate or edible object"],
    compatibleArchetypes: ["premium-product", "product-hero", "numeric-proof"],
  },
  {
    id: "agriculture-farm-fresh",
    label: "산지 신선함",
    categoryMatchers: ["농산물", "산지직송", "신선식품", "과일", "채소"],
    benefitMatchers: ["신선", "산지", "직송", "제철", "정직"],
    visualMood: ["fresh", "honest", "sunlit", "trustworthy"],
    environment: ["generic sunlit farm edge", "clean harvest field without location markers"],
    props: ["wood crate", "soft leaves", "clean natural soil used sparingly"],
    lighting: ["morning sunlight", "soft warm rim", "natural fill"],
    textures: ["wood", "leaf", "woven basket"],
    colorHints: ["#347b3d", "#f1bd3f", "#fff9e8", "#6a452c"],
    compositionRules: ["no identifiable region", "reserve a clean foreground stage", "natural depth not stock-like"],
    productSafeZoneRules: ["lower-center or center-right 52% x 52%"],
    textSafeZoneRules: ["upper-left 52% x 30% with sky or soft foliage"],
    negativePromptRules: [...sharedNegatives, "no fruit, vegetable, harvested crop or produce pile anywhere", "no farmer identity", "no certification mark", "no different crop variety"],
    compatibleArchetypes: ["lifestyle-context", "product-hero", "seasonal-context"],
  },
  {
    id: "agriculture-harvest",
    label: "제철 수확",
    categoryMatchers: ["농산물", "산지직송", "신선식품", "과일", "채소"],
    benefitMatchers: ["수확", "제철", "푸짐", "산지", "생산자"],
    visualMood: ["abundant harvest", "seasonal", "warm", "realistic"],
    environment: ["harvest worktable near a field", "sunlit packing shed"],
    props: ["basket", "kraft packing paper", "wood crate"],
    lighting: ["late-morning sunlight", "warm bounce", "soft contact shadows"],
    textures: ["kraft paper", "wood", "natural fiber"],
    colorHints: ["#4a833f", "#e6a636", "#f7f0dc", "#a45d2b"],
    compositionRules: ["generic setting only", "product placement surface stays uncluttered and fully rendered", "background foliage is abstracted and out of focus"],
    productSafeZoneRules: ["center 56% x 50%"],
    textSafeZoneRules: ["top 100% x 25% calm wall or sky"],
    negativePromptRules: [...sharedNegatives, "no fruit, vegetable, harvested crop or produce pile anywhere", "no false region signage", "no fake product pile in safe zone"],
    compatibleArchetypes: ["seasonal-context", "three-benefits", "product-hero"],
  },
  {
    id: "agriculture-direct-value",
    label: "산지직송 실속",
    categoryMatchers: ["농산물", "산지직송", "신선식품", "식품"],
    benefitMatchers: ["직송", "가격", "구성", "무료배송", "실속"],
    visualMood: ["direct commerce", "honest value", "fresh", "energetic"],
    environment: ["clean packing table", "bright farm-commerce set"],
    props: ["shipping box without labels", "kraft paper", "small harvest basket"],
    lighting: ["bright daylight", "clear contact shadow", "warm natural edge light"],
    textures: ["kraft", "wood", "clean matte surface"],
    colorHints: ["#f6f0dc", "#34843f", "#e3432f", "#f1b82d"],
    compositionRules: ["large bottom offer zone", "hero opening at center-right", "top headline field"],
    productSafeZoneRules: ["center-right 50% x 54%"],
    textSafeZoneRules: ["upper-left 50% x 30%", "bottom 100% x 18%"],
    negativePromptRules: [...sharedNegatives, "no fruit, vegetable, harvested crop or produce pile anywhere", "no shipping label", "no fake farm name", "no certification"],
    compatibleArchetypes: ["price-event", "numeric-proof", "three-benefits"],
  },
  {
    id: "agriculture-clean-commerce",
    label: "클린 농산물 커머스",
    categoryMatchers: ["농산물", "산지직송", "신선식품", "식품"],
    benefitMatchers: ["깨끗", "포장", "신선", "가정", "구성"],
    visualMood: ["clean commerce", "bright", "organized", "fresh"],
    environment: ["bright neutral kitchen or packing set", "soft botanical depth"],
    props: ["neutral ceramic", "linen", "small wood board"],
    lighting: ["large daylight softbox", "gentle warm rim", "soft contact shadow"],
    textures: ["linen", "light wood", "ceramic"],
    colorHints: ["#fffdf7", "#dfead5", "#4f7e4c", "#d95b3f"],
    compositionRules: ["minimal but not empty", "center product stage", "top-left text field"],
    productSafeZoneRules: ["center-right 48% x 55%"],
    textSafeZoneRules: ["upper-left 50% x 32%"],
    negativePromptRules: [...sharedNegatives, "no fruit, vegetable, harvested crop or produce pile anywhere", "no fake produce variety", "no excessive water droplets"],
    compatibleArchetypes: ["product-hero", "three-benefits", "premium-product"],
  },
  {
    id: "generic-bold-performance",
    label: "볼드 퍼포먼스",
    categoryMatchers: ["기타", "일반"],
    benefitMatchers: ["특가", "혜택", "새로움", "해결"],
    visualMood: ["bold commerce", "high contrast", "dynamic", "clear"],
    environment: ["layered studio set with category-neutral depth"],
    props: ["abstract planes", "soft light streak", "ground pedestal"],
    lighting: ["directional key", "controlled rim", "clear ground shadow"],
    textures: ["matte studio", "subtle acrylic"],
    colorHints: ["#1769e0", "#0e1725", "#ffffff", "#ffcf33"],
    compositionRules: ["upper-left hook zone", "center-right product zone", "bottom offer zone"],
    productSafeZoneRules: ["center-right 46% x 60%"],
    textSafeZoneRules: ["upper-left 50% x 32%", "bottom 100% x 15%"],
    negativePromptRules: sharedNegatives,
    compatibleArchetypes: ["giant-hook", "product-hero", "problem-solution"],
  },
  {
    id: "generic-clean-brand",
    label: "클린 브랜드",
    categoryMatchers: ["기타", "일반"],
    benefitMatchers: ["프리미엄", "품질", "신뢰", "선물"],
    visualMood: ["clean", "quietly premium", "modern", "trustworthy"],
    environment: ["minimal studio with depth and material contrast"],
    props: ["single pedestal", "one contextual texture"],
    lighting: ["soft key", "subtle rim", "clean contact shadow"],
    textures: ["matte wall", "stone or acrylic surface"],
    colorHints: ["#f8fafc", "#dce6ee", "#172033"],
    compositionRules: ["generous whitespace", "product remains large", "one text column"],
    productSafeZoneRules: ["center-right 44% x 58%"],
    textSafeZoneRules: ["left 48% x 42%"],
    negativePromptRules: sharedNegatives,
    compatibleArchetypes: ["product-hero", "premium-product", "three-benefits"],
  },
  {
    id: "generic-price-event",
    label: "가격 이벤트",
    categoryMatchers: ["기타", "일반", "커머스"],
    benefitMatchers: ["가격", "할인", "특가", "구성", "이벤트"],
    visualMood: ["high-conversion", "clear", "urgent", "product-led"],
    environment: ["dark-to-light commerce stage with strong depth"],
    props: ["subtle diagonal energy", "ground platform"],
    lighting: ["bright product rim", "dark surrounding field", "warm accent"],
    textures: ["matte stage", "subtle gloss"],
    colorHints: ["#111111", "#ef2727", "#ffe51f", "#ffffff"],
    compositionRules: ["keep top hook and bottom price zones quiet", "product fills middle"],
    productSafeZoneRules: ["center 58% x 54%"],
    textSafeZoneRules: ["top 100% x 24%", "bottom 100% x 20%"],
    negativePromptRules: sharedNegatives,
    compatibleArchetypes: ["price-event", "numeric-proof", "giant-hook"],
  },
];

export function getSceneProfile(id: string) {
  return sceneProfiles.find((profile) => profile.id === id) || sceneProfiles[0];
}
