import type { TextStylePreset } from "./types";

const sans = '"Pretendard", "Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif';

export const creativeTextStylePresets: TextStylePreset[] = [
  {
    id: "cooling-impact",
    label: "쿨링 임팩트",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.16,
    secondaryScale: 0.94,
    letterSpacing: -3,
    lineHeight: 0.96,
    foregroundColor: "#ffffff",
    outline: { color: "#0a5e78", width: 5 },
    shadow: { color: "rgba(0,55,78,.45)", blur: 12, offsetX: 0, offsetY: 7 },
    highlightColors: ["#00e8c5", "#0aa9ef", "#ffffff"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [8, 24],
  },
  {
    id: "bold-performance",
    label: "볼드 퍼포먼스",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.15,
    secondaryScale: 0.96,
    letterSpacing: -3,
    lineHeight: 0.98,
    foregroundColor: "#ffffff",
    outline: { color: "#111111", width: 5 },
    shadow: { color: "rgba(0,0,0,.45)", blur: 10, offsetX: 0, offsetY: 6 },
    highlightColors: ["#ffe61f", "#ff3030", "#ffffff"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [7, 22],
  },
  {
    id: "community-review",
    label: "커뮤니티 후기",
    fontFamily: sans,
    fontWeight: 800,
    headlineScale: 0.98,
    secondaryScale: 0.9,
    letterSpacing: -1,
    lineHeight: 1.08,
    foregroundColor: "#ffffff",
    backgroundBox: { color: "#111111", opacity: 0.94, paddingRatio: 0.04 },
    highlightColors: ["#21e4c5", "#ffffff", "#111111"],
    recommendedLineCount: 3,
    recommendedCharacterRange: [10, 30],
  },
  {
    id: "clean-brand",
    label: "클린 브랜드",
    fontFamily: sans,
    fontWeight: 800,
    headlineScale: 1.02,
    secondaryScale: 0.88,
    letterSpacing: -1,
    lineHeight: 1.06,
    foregroundColor: "#15202b",
    shadow: { color: "rgba(0,0,0,.12)", blur: 6, offsetX: 0, offsetY: 3 },
    highlightColors: ["#17c7ad", "#1769e0", "#15202b"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [9, 26],
  },
  {
    id: "premium-food",
    label: "프리미엄 푸드",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.12,
    secondaryScale: 0.92,
    letterSpacing: -2,
    lineHeight: 0.98,
    foregroundColor: "#ffffff",
    outline: { color: "#1a120e", width: 5 },
    shadow: { color: "rgba(0,0,0,.55)", blur: 13, offsetX: 0, offsetY: 7 },
    highlightColors: ["#ffd51c", "#e92920", "#ffffff"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [7, 23],
  },
  {
    id: "honest-farm-direct",
    label: "솔직한 산지직송",
    fontFamily: sans,
    fontWeight: 850,
    headlineScale: 1.04,
    secondaryScale: 0.9,
    letterSpacing: -1,
    lineHeight: 1.03,
    foregroundColor: "#18321d",
    backgroundBox: { color: "#fffdf6", opacity: 0.9, paddingRatio: 0.035 },
    highlightColors: ["#34843f", "#e6a636", "#d94431"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [9, 25],
  },
  {
    id: "price-commerce",
    label: "가격 커머스",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.18,
    secondaryScale: 0.94,
    letterSpacing: -4,
    lineHeight: 0.94,
    foregroundColor: "#ffffff",
    outline: { color: "#111111", width: 6 },
    shadow: { color: "rgba(0,0,0,.5)", blur: 8, offsetX: 0, offsetY: 6 },
    highlightColors: ["#ff1f1f", "#fff000", "#ffffff"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [6, 20],
  },
  {
    id: "seasonal-impact",
    label: "시즌 임팩트",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.1,
    secondaryScale: 0.92,
    letterSpacing: -2,
    lineHeight: 0.98,
    foregroundColor: "#ffffff",
    outline: { color: "#17202b", width: 4 },
    shadow: { color: "rgba(0,0,0,.38)", blur: 10, offsetX: 0, offsetY: 5 },
    highlightColors: ["#ffe431", "#1ed2a4", "#ef3f36"],
    recommendedLineCount: 2,
    recommendedCharacterRange: [8, 24],
  },
  {
    id: "lifestyle-problem-solution",
    label: "일상 문제 해결",
    fontFamily: sans,
    fontWeight: 900,
    headlineScale: 1.08,
    secondaryScale: 0.9,
    letterSpacing: -2,
    lineHeight: 1,
    foregroundColor: "#ffffff",
    outline: { color: "#151515", width: 4 },
    backgroundBox: { color: "#111111", opacity: 0.72, paddingRatio: 0.03 },
    highlightColors: ["#21dcb8", "#ff3a37", "#ffffff"],
    recommendedLineCount: 3,
    recommendedCharacterRange: [10, 28],
  },
];

export function getCreativeTextStylePreset(id: string) {
  return creativeTextStylePresets.find((preset) => preset.id === id) || creativeTextStylePresets[1];
}
