import type { VisualArchetype } from "./types";

export const visualArchetypes: VisualArchetype[] = [
  {
    id: "giant-hook",
    name: "초대형 후킹형",
    suitableStrategies: ["문제 직격", "강한 혜택", "놀람", "반전"],
    suitableCategories: ["퍼스널케어", "식품", "농산물", "생활용품"],
    textHierarchy: ["headline", "product", "proof", "cta"],
    recommendedProductCount: [1, 2],
    productPlacement: "center-right hero with a clear upper text field",
    sceneConditions: ["large quiet headline zone", "strong product/background separation"],
    graphicComponents: ["GiantHeadline", "HighlightBox", "ProductHalo", "FooterBar", "CTAStrip"],
    useFooterBar: true,
    ctaPosition: "bottom strip",
    textSafeArea: "top 30% or left 42%",
    recommendedIntensity: ["performance", "balanced"],
    avoid: ["three equal messages", "small product", "busy headline background"],
  },
  {
    id: "problem-solution",
    name: "문제-해결형",
    suitableStrategies: ["소비자 불편", "결핍", "사용 전후", "공감"],
    suitableCategories: ["퍼스널케어", "생활용품", "식품"],
    textHierarchy: ["problem hook", "solution product", "benefit", "cta"],
    recommendedProductCount: [1],
    productPlacement: "right hero or lower-center solution reveal",
    sceneConditions: ["recognizable use context", "contrast between problem and solution zones"],
    graphicComponents: ["GiantHeadline", "BenefitChip", "ScribbleArrow", "ProductOutline", "CTAButton"],
    useFooterBar: false,
    ctaPosition: "lower-left or bottom",
    textSafeArea: "left 48%",
    recommendedIntensity: ["performance", "balanced"],
    avoid: ["unverified before-after claim", "medical-looking proof without facts"],
  },
  {
    id: "numeric-proof",
    name: "숫자 근거형",
    suitableStrategies: ["확인된 수치", "구성", "중량", "가격", "리뷰"],
    suitableCategories: ["퍼스널케어", "식품", "농산물", "건강식품"],
    textHierarchy: ["headline", "verified number", "product", "supporting fact"],
    recommendedProductCount: [1, 3],
    productPlacement: "center hero with proof adjacent",
    sceneConditions: ["clean contrast field behind numbers", "limited decorative noise"],
    graphicComponents: ["GiantHeadline", "NumericBadge", "BenefitChip", "EmphasisUnderline", "FooterBar"],
    useFooterBar: true,
    ctaPosition: "bottom-right",
    textSafeArea: "top and lower-left",
    recommendedIntensity: ["performance", "balanced"],
    avoid: ["invented metrics", "more than three competing numbers"],
  },
  {
    id: "product-hero",
    name: "제품 단독 임팩트형",
    suitableStrategies: ["상품 발견", "상품력", "감각", "품질"],
    suitableCategories: ["퍼스널케어", "식품", "뷰티", "패션"],
    textHierarchy: ["headline", "product", "single benefit", "cta"],
    recommendedProductCount: [1],
    productPlacement: "center or center-right at 48-65% canvas height",
    sceneConditions: ["cinematic depth", "clear grounding surface", "directional rim light"],
    graphicComponents: ["GiantHeadline", "ProductHalo", "ProductShadow", "ProductOutline", "CTAButton"],
    useFooterBar: false,
    ctaPosition: "bottom-left",
    textSafeArea: "top 28%",
    recommendedIntensity: ["brand", "balanced", "performance"],
    avoid: ["small floating product", "fake package generation"],
  },
  {
    id: "three-benefits",
    name: "3포인트 소구형",
    suitableStrategies: ["다중 혜택", "구성 설명", "사용 이유"],
    suitableCategories: ["퍼스널케어", "농산물", "건강식품", "리빙"],
    textHierarchy: ["headline", "three benefits", "product", "cta"],
    recommendedProductCount: [1, 3],
    productPlacement: "product row or one hero beside three chips",
    sceneConditions: ["organized clean field", "consistent icon/chip rhythm"],
    graphicComponents: ["SubHeadline", "ThreeBenefitRow", "BenefitChip", "ProductShadow", "CTAStrip"],
    useFooterBar: true,
    ctaPosition: "bottom strip",
    textSafeArea: "top 22% and one side column",
    recommendedIntensity: ["balanced", "brand"],
    avoid: ["long benefit sentences", "four or more equal benefits"],
  },
  {
    id: "community-review",
    name: "커뮤니티·후기형",
    suitableStrategies: ["사용자 반응", "공감", "입소문", "UGC"],
    suitableCategories: ["퍼스널케어", "생활용품", "식품", "앱"],
    textHierarchy: ["review hook", "community card", "product", "response/cta"],
    recommendedProductCount: [1, 3],
    productPlacement: "bottom-right or beside review card",
    sceneConditions: ["dark or neutral UI-like field", "card contrast"],
    graphicComponents: ["CommunityPostCard", "ReviewCard", "HashtagPill", "ProductOutline", "CTAButton"],
    useFooterBar: false,
    ctaPosition: "within response card or bottom-right",
    textSafeArea: "center-left card",
    recommendedIntensity: ["performance", "balanced"],
    avoid: ["fake review count", "impersonating a real platform exactly"],
  },
  {
    id: "seasonal-context",
    name: "시즌 이슈형",
    suitableStrategies: ["여름", "캠핑", "제철", "명절", "모임"],
    suitableCategories: ["식품", "농산물", "퍼스널케어", "패션"],
    textHierarchy: ["season hook", "product", "occasion benefit", "urgency"],
    recommendedProductCount: [1, 2],
    productPlacement: "foreground in a contextual scene",
    sceneConditions: ["season cues without fake location", "clear product safe zone"],
    graphicComponents: ["GiantHeadline", "AccentRibbon", "BenefitChip", "GradientScrim", "CTAStrip"],
    useFooterBar: true,
    ctaPosition: "bottom strip",
    textSafeArea: "top-left",
    recommendedIntensity: ["balanced", "performance"],
    avoid: ["unrelated seasonal prop overload", "false limited-time claims"],
  },
  {
    id: "price-event",
    name: "가격·행사형",
    suitableStrategies: ["가격 충격", "할인", "구성", "가격 정당화"],
    suitableCategories: ["식품", "농산물", "생활용품", "뷰티"],
    textHierarchy: ["price hook", "product", "price block", "urgency/cta"],
    recommendedProductCount: [1, 2, 3],
    productPlacement: "large middle product with grouped price block",
    sceneConditions: ["high-contrast offer zone", "product remains dominant"],
    graphicComponents: ["GiantHeadline", "NumericBadge", "AccentRibbon", "FooterBar", "CTAStrip"],
    useFooterBar: true,
    ctaPosition: "full-width bottom",
    textSafeArea: "top 25% and bottom 20%",
    recommendedIntensity: ["performance"],
    avoid: ["scattered price fragments", "unverified discount rate"],
  },
  {
    id: "lifestyle-context",
    name: "사용 상황형",
    suitableStrategies: ["일상 상황", "공감", "선물", "가족", "운동 후"],
    suitableCategories: ["퍼스널케어", "식품", "농산물", "리빙"],
    textHierarchy: ["context hook", "product/use scene", "benefit", "cta"],
    recommendedProductCount: [1],
    productPlacement: "within a believable use scene, still visually isolated",
    sceneConditions: ["authentic context", "shallow depth", "text contrast zone"],
    graphicComponents: ["SubHeadline", "HighlightBox", "ScribbleArrow", "ProductShadow", "CTAButton"],
    useFooterBar: false,
    ctaPosition: "bottom-right",
    textSafeArea: "opposite the product",
    recommendedIntensity: ["brand", "balanced"],
    avoid: ["generic stock-photo composition", "product hidden by people or props"],
  },
  {
    id: "premium-product",
    name: "프리미엄 상품형",
    suitableStrategies: ["품질", "선물 명분", "소재", "신뢰", "품격"],
    suitableCategories: ["식품", "선물", "뷰티", "패션"],
    textHierarchy: ["quality hook", "product", "proof", "price/cta"],
    recommendedProductCount: [1, 2],
    productPlacement: "hero on a premium surface with controlled light",
    sceneConditions: ["restrained props", "directional light", "rich but clean texture"],
    graphicComponents: ["SubHeadline", "EmphasisUnderline", "ProductHalo", "ProductShadow", "CTAButton"],
    useFooterBar: false,
    ctaPosition: "lower-right",
    textSafeArea: "top-left or left column",
    recommendedIntensity: ["brand", "balanced"],
    avoid: ["meme tone", "neon price clutter", "excessive badges"],
  },
];

export function getVisualArchetype(id: string) {
  return visualArchetypes.find((archetype) => archetype.id === id) || visualArchetypes[0];
}
