import type {
  PalettePolicy,
  TemplateCopyLimits,
  TemplateSlot,
  TemplateVariantPreference,
} from "../app/lib/mvp/types";

export type HeadlineFontPresetId =
  "impact-korean-red" | "commerce-heavy-black" | "premium-serif-gold" | "ugc-bold-white";

export type HeadlineFontPreset = {
  description: string;
  fontFamily: string;
  fontWeight: number;
  letterSpacing: number;
  lineHeight: number;
  color: string;
  textStroke?: boolean;
  textStrokeColor?: string;
  textStrokeWidth?: number;
  textShadow?: boolean;
  shadowColor?: string;
  shadowBlur?: number;
  shadowOffsetX?: number;
  shadowOffsetY?: number;
};

export const headlineFontPresets: Record<HeadlineFontPresetId, HeadlineFontPreset> = {
  "impact-korean-red": {
    description: "식품/공구형 광고의 초두꺼운 빨간 헤드라인",
    fontFamily:
      '"Black Han Sans", Pretendard, "Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif',
    fontWeight: 900,
    letterSpacing: -4,
    lineHeight: 0.95,
    color: "#ff1f1f",
    textShadow: true,
    shadowColor: "rgba(255, 31, 31, 0.18)",
    shadowBlur: 0,
    shadowOffsetX: 1,
    shadowOffsetY: 2,
  },
  "commerce-heavy-black": {
    description: "검정색 굵은 설명형 헤드라인",
    fontFamily: '"Do Hyeon", "Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif',
    fontWeight: 400,
    letterSpacing: -2,
    lineHeight: 1.05,
    color: "#111111",
  },
  "premium-serif-gold": {
    description: "선물/고급감 템플릿용 묵직한 골드 톤",
    fontFamily: '"Gowun Batang", "Noto Serif KR", serif',
    fontWeight: 700,
    letterSpacing: -1,
    lineHeight: 1.1,
    color: "#d6a84f",
  },
  "ugc-bold-white": {
    description: "배경 이미지 위에 얹는 흰색 UGC형 손글씨 문구",
    fontFamily:
      '"Nanum Pen Script", "Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif',
    fontWeight: 400,
    letterSpacing: -1,
    lineHeight: 1.05,
    color: "#ffffff",
    textStroke: true,
    textStrokeColor: "#111111",
    textStrokeWidth: 4,
  },
};

export const templateHeadlinePresetMap: Record<string, HeadlineFontPresetId> = {
  "shock-headline-001": "impact-korean-red",
  "food-impact-hero-001": "impact-korean-red",
  "food-template-001": "impact-korean-red",
  "food-template-002": "impact-korean-red",
  "food-template-003": "premium-serif-gold",
  "food-template-004": "commerce-heavy-black",
  "food-template-005": "ugc-bold-white",
  "camping-popularity-impact": "impact-korean-red",
  "circle-focus-review": "commerce-heavy-black",
  "black-repeat-product": "ugc-bold-white",
  "sports-benefit-chip": "ugc-bold-white",
  "before-after-split-review": "commerce-heavy-black",
  "bold-commerce-001": "impact-korean-red",
  "price-proof-002": "impact-korean-red",
  "home-shopping-max-010": "impact-korean-red",
  "premium-gift-006": "premium-serif-gold",
  "ugc-meme-005": "ugc-bold-white",
  "auto-meat-impact-001": "impact-korean-red",
  "auto-produce-market-001": "premium-serif-gold",
  "auto-beauty-editorial-001": "premium-serif-gold",
  "auto-beauty-proof-002": "commerce-heavy-black",
  "auto-body-solution-001": "impact-korean-red",
};

export type BannerTemplateDefinition = {
  id: string;
  name: string;
  category: string;
  templateGroup: string;
  description: string;
  recommendedHookTypes: string[];
  recommendedAppealPoints: string[];
  style: Record<string, string | number | boolean>;
  typography: Record<string, number>;
  zones: Record<string, string>;
  copyLimits?: TemplateCopyLimits;
  renderMode?: "legacy" | "slot-engine";
  visualTone?: string;
  palettePolicy?: PalettePolicy;
  textStylePresetKey?: string;
  variantPreference?: TemplateVariantPreference;
  slots?: TemplateSlot[];
  safeArea?: { top: number; right: number; bottom: number; left: number };
  supportsMultipleImages?: boolean;
  maximumImageCount?: number;
  optimizationEnabled?: boolean;
};

export const foodTemplateCopyLimits: Record<string, TemplateCopyLimits> = {
  "food-template-001": {
    headline: {
      maxChars: 28,
      maxLines: 2,
      minFontSize: 52,
      maxFontSize: 86,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 22,
      maxLines: 1,
      minFontSize: 26,
      maxFontSize: 40,
      overflowStrategy: "shrink-ellipsis",
    },
    highlightCopy: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 26,
      maxFontSize: 42,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 8,
      maxLines: 1,
      minFontSize: 18,
      maxFontSize: 28,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 52,
      maxFontSize: 86,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "food-template-002": {
    headline: {
      maxChars: 12,
      maxLines: 2,
      minFontSize: 52,
      maxFontSize: 92,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 34,
      maxLines: 2,
      minFontSize: 24,
      maxFontSize: 34,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 24,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 28,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 8,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 32,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 48,
      maxFontSize: 82,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "food-template-003": {
    headline: {
      maxChars: 18,
      maxLines: 2,
      minFontSize: 34,
      maxFontSize: 48,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 44,
      maxLines: 2,
      minFontSize: 18,
      maxFontSize: 30,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 24,
      maxLines: 2,
      minFontSize: 20,
      maxFontSize: 34,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 30,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 20,
      maxFontSize: 30,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 34,
      maxFontSize: 60,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "food-template-004": {
    headline: {
      maxChars: 20,
      maxLines: 2,
      minFontSize: 42,
      maxFontSize: 78,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 50,
      maxLines: 3,
      minFontSize: 20,
      maxFontSize: 34,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 22,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 32,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 30,
      maxLines: 2,
      minFontSize: 22,
      maxFontSize: 32,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 20,
      maxFontSize: 30,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 34,
      maxFontSize: 54,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "food-template-005": {
    headline: {
      maxChars: 16,
      maxLines: 2,
      minFontSize: 52,
      maxFontSize: 92,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 36,
      maxLines: 2,
      minFontSize: 24,
      maxFontSize: 36,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 24,
      maxLines: 1,
      minFontSize: 28,
      maxFontSize: 48,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 30,
      maxLines: 1,
      minFontSize: 26,
      maxFontSize: 42,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 20,
      maxFontSize: 30,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 50,
      maxFontSize: 96,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "camping-popularity-impact": {
    headline: {
      maxChars: 30,
      maxLines: 2,
      minFontSize: 58,
      maxFontSize: 130,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 28,
      maxLines: 1,
      minFontSize: 34,
      maxFontSize: 64,
      overflowStrategy: "shrink-ellipsis",
    },
    highlightCopy: {
      maxChars: 14,
      maxLines: 1,
      minFontSize: 32,
      maxFontSize: 54,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 32,
      maxLines: 1,
      minFontSize: 32,
      maxFontSize: 58,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 28,
      maxLines: 1,
      minFontSize: 34,
      maxFontSize: 58,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 14,
      maxLines: 1,
      minFontSize: 52,
      maxFontSize: 82,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "circle-focus-review": {
    headline: {
      maxChars: 34,
      maxLines: 3,
      minFontSize: 42,
      maxFontSize: 78,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 22,
      maxLines: 2,
      minFontSize: 28,
      maxFontSize: 46,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 38,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 18,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 20,
      maxFontSize: 30,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 26,
      maxFontSize: 40,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "black-repeat-product": {
    headline: {
      maxChars: 28,
      maxLines: 2,
      minFontSize: 58,
      maxFontSize: 112,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 24,
      maxLines: 1,
      minFontSize: 30,
      maxFontSize: 52,
      overflowStrategy: "shrink-ellipsis",
    },
    highlightCopy: {
      maxChars: 22,
      maxLines: 1,
      minFontSize: 28,
      maxFontSize: 46,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 38,
      maxLines: 1,
      minFontSize: 28,
      maxFontSize: 44,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 20,
      maxFontSize: 30,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 14,
      maxLines: 1,
      minFontSize: 30,
      maxFontSize: 44,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "sports-benefit-chip": {
    headline: {
      maxChars: 32,
      maxLines: 5,
      minFontSize: 40,
      maxFontSize: 78,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 18,
      maxLines: 1,
      minFontSize: 26,
      maxFontSize: 42,
      overflowStrategy: "shrink-ellipsis",
    },
    highlightCopy: {
      maxChars: 16,
      maxLines: 1,
      minFontSize: 28,
      maxFontSize: 44,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 16,
      maxLines: 1,
      minFontSize: 28,
      maxFontSize: 42,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 24,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 36,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 36,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "before-after-split-review": {
    headline: {
      maxChars: 34,
      maxLines: 5,
      minFontSize: 38,
      maxFontSize: 72,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 24,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 36,
      overflowStrategy: "shrink-ellipsis",
    },
    highlightCopy: {
      maxChars: 16,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 36,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 18,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 14,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 38,
      overflowStrategy: "shrink-ellipsis",
    },
  },
  "food-impact-hero-001": {
    headline: {
      maxChars: 16,
      maxLines: 2,
      minFontSize: 56,
      maxFontSize: 108,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    bodyCopy: {
      maxChars: 40,
      maxLines: 2,
      minFontSize: 28,
      maxFontSize: 43,
      overflowStrategy: "shrink-wrap-ellipsis",
    },
    highlightCopy: {
      maxChars: 26,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 35,
      overflowStrategy: "shrink-ellipsis",
    },
    bottomBarCopy: {
      maxChars: 30,
      maxLines: 1,
      minFontSize: 24,
      maxFontSize: 37,
      overflowStrategy: "shrink-ellipsis",
    },
    cta: {
      maxChars: 10,
      maxLines: 1,
      minFontSize: 22,
      maxFontSize: 34,
      overflowStrategy: "shrink-ellipsis",
    },
    price: {
      maxChars: 12,
      maxLines: 1,
      minFontSize: 36,
      maxFontSize: 56,
      overflowStrategy: "shrink-ellipsis",
    },
  },
};

const baseFoodFont = '"Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif';

export const foodCategoryTemplates: BannerTemplateDefinition[] = [
  {
    id: "food-template-001",
    name: "분할 고기 특가형",
    category: "식품/선물",
    templateGroup: "food",
    description:
      "좌우 분할 상품 비주얼과 하단 가격 블록으로 선물/고기 특가감을 강하게 보여주는 템플릿입니다.",
    recommendedHookTypes: ["감탄형", "가격정당화형", "가격충격형", "긴급/한정형"],
    recommendedAppealPoints: ["가성비", "실속", "즉시혜택", "후기신뢰"],
    style: {
      backgroundColor: "#ffffff",
      headlineColor: "#ff1f1f",
      bodyColor: "#111111",
      highlightBackground: "#ffe600",
      highlightTextColor: "#111111",
      bottomBarColor: "#ff1f1f",
      bottomBarTextColor: "#ffffff",
      ctaBarColor: "#e58585",
      ctaTextColor: "#ffffff",
      priceColor: "#ff1f1f",
      accentColor: "#ffe600",
      headlineFontPreset: "impact-korean-red",
      headlineFontWeight: 900,
      headlineLetterSpacing: -4,
      headlineLineHeight: 0.95,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 112,
      bodyFontSize: 42,
      highlightFontSize: 36,
      bottomBarFontSize: 36,
      ctaFontSize: 32,
    },
    zones: {
      headline: "top",
      body: "top-mid",
      highlight: "mid-band",
      product: "center-large",
      bottom: "bottom-bar",
      cta: "bottom-pill",
    },
    copyLimits: foodTemplateCopyLimits["food-template-001"],
  },
  {
    id: "food-template-002",
    name: "가격 폭발 특가형",
    category: "식품/선물",
    templateGroup: "food",
    description:
      "고기 이미지를 전체 배경으로 깔고 후기 박스, 원가/특가, 하단 대형 오드라인을 강조하는 식품 특가 템플릿입니다.",
    recommendedHookTypes: ["가격정당화형", "가격소구형", "긴급/한정형"],
    recommendedAppealPoints: ["가성비", "실속", "즉시혜택"],
    style: {
      backgroundColor: "#111111",
      headlineColor: "#ffffff",
      bodyColor: "#111111",
      highlightBackground: "#ffe600",
      highlightTextColor: "#111111",
      badgeColor: "#ffe600",
      bottomBarColor: "#111111",
      bottomBarTextColor: "#ffffff",
      ctaBarColor: "#ff1f1f",
      ctaTextColor: "#ffffff",
      priceColor: "#ff1f1f",
      priceStrokeColor: "#ffffff",
      priceStrokeWidth: 8,
      accentColor: "#ffe600",
      headlineFontPreset: "impact-korean-red",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 112,
      bodyFontSize: 38,
      highlightFontSize: 96,
      bottomBarFontSize: 34,
      ctaFontSize: 32,
    },
    zones: {
      background: "full-bleed-meat",
      headline: "top-left-review-box",
      price: "center-original-sale",
      highlight: "bottom-main-offer",
    },
    copyLimits: foodTemplateCopyLimits["food-template-002"],
  },
  {
    id: "food-template-003",
    name: "미니멀 비교 설명형",
    category: "식품/선물",
    templateGroup: "food",
    description:
      "흰 배경 2단 비교 레이아웃으로 설명형/브랜드형 상품을 차분하게 보여주는 템플릿입니다.",
    recommendedHookTypes: ["선물명분형", "가격정당화형", "전문가/권위형"],
    recommendedAppealPoints: ["선물명분", "고급감", "실속", "사회적 인정"],
    style: {
      backgroundColor: "#15100c",
      headlineColor: "#f7d27a",
      bodyColor: "#fff7e6",
      highlightBackground: "#3a2416",
      highlightTextColor: "#f7d27a",
      bottomBarColor: "#2b1a10",
      bottomBarTextColor: "#fff7e6",
      ctaBarColor: "#b8893b",
      ctaTextColor: "#ffffff",
      priceColor: "#f7d27a",
      accentColor: "#b8893b",
      headlineFontPreset: "premium-serif-gold",
      headlineFontWeight: 800,
      headlineLetterSpacing: -1,
      fontFamily: '"Noto Serif KR", serif',
    },
    typography: {
      headlineFontSize: 84,
      bodyFontSize: 36,
      highlightFontSize: 32,
      bottomBarFontSize: 30,
      ctaFontSize: 30,
    },
    zones: {
      headline: "top-premium",
      product: "center-framed",
      body: "bottom-copy",
      highlight: "gold-label",
      price: "subtle",
      cta: "gold-button",
    },
    copyLimits: foodTemplateCopyLimits["food-template-003"],
  },
  {
    id: "food-template-004",
    name: "후기 말풍선 UGC형",
    category: "식품/선물",
    templateGroup: "food",
    description: "실제 구매 후기나 SNS 반응처럼 보이는 후기/UGC형 식품 리뷰 템플릿입니다.",
    recommendedHookTypes: ["후기/리뷰형", "UGC형", "공감형", "반전/궁금증형"],
    recommendedAppealPoints: ["후기신뢰", "가성비", "실속", "감정적 공감"],
    style: {
      backgroundColor: "#fff8ef",
      headlineColor: "#111111",
      bodyColor: "#222222",
      highlightBackground: "#ffffff",
      highlightTextColor: "#111111",
      accentColor: "#ff5a2f",
      bottomBarColor: "#ff5a2f",
      bottomBarTextColor: "#ffffff",
      ctaBarColor: "#111111",
      ctaTextColor: "#ffffff",
      priceColor: "#ff5a2f",
      headlineFontPreset: "commerce-heavy-black",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 78,
      bodyFontSize: 34,
      highlightFontSize: 32,
      bottomBarFontSize: 32,
      ctaFontSize: 30,
    },
    zones: {
      headline: "review-top",
      body: "speech-card",
      product: "center-photo",
      highlight: "reaction-card",
      cta: "bottom-dark",
    },
    copyLimits: foodTemplateCopyLimits["food-template-004"],
  },
  {
    id: "food-template-005",
    name: "다크 임팩트 공구형",
    category: "식품/선물",
    templateGroup: "food",
    description:
      "어두운 배경 위에 대형 문구, 전면 상품, 흰 외곽선 가격을 쌓아 공구 광고처럼 강하게 보이는 템플릿입니다.",
    recommendedHookTypes: ["감탄형", "가격충격형", "선물명분형", "긴급/한정형"],
    recommendedAppealPoints: ["고급감", "가성비", "실속", "즉시혜택"],
    style: {
      backgroundColor: "#111111",
      backgroundMode: "auto-detail-blur-dark",
      backgroundBlur: "high",
      backgroundDarkOverlay: 0.55,
      headlineColor: "#ffe600",
      headlineTextStroke: true,
      headlineTextStrokeColor: "#111111",
      headlineTextStrokeWidth: 4,
      bodyColor: "#ffffff",
      highlightBackground: "#111111",
      highlightTextColor: "#ffe600",
      bottomBarColor: "#ff1f1f",
      bottomBarTextColor: "#ffffff",
      ctaBarColor: "#ff1f1f",
      ctaTextColor: "#ffffff",
      priceColor: "#ff1f1f",
      priceStrokeColor: "#ffffff",
      priceStrokeWidth: 6,
      accentColor: "#ffe600",
      headlineFontPreset: "ugc-bold-white",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 92,
      bodyFontSize: 36,
      highlightFontSize: 30,
      bottomBarFontSize: 34,
      ctaFontSize: 30,
    },
    zones: {
      background: "full-bleed-blur",
      headline: "top-overlay",
      product: "center-foreground",
      price: "bottom-large",
      cta: "bottom-red",
    },
    copyLimits: foodTemplateCopyLimits["food-template-005"],
  },
  {
    id: "camping-popularity-impact",
    name: "캠핑인기폭발형",
    category: "범용/특가",
    templateGroup: "new-reference",
    description:
      "상단 초대형 레드 헤드라인, 빨간 가격띠, 대형 상품 이미지, 하단 CTA로 구성한 인기 폭발형 광고 템플릿입니다.",
    recommendedHookTypes: ["가격정당화형", "긴급/한정형", "상황제안형", "문제제기형"],
    recommendedAppealPoints: ["가격", "인기감", "상황명분", "즉시구매"],
    style: {
      backgroundColor: "#ffffff",
      headlineColor: "#e60000",
      bodyColor: "#111111",
      highlightBackground: "#fff200",
      highlightTextColor: "#111111",
      bottomBarColor: "#e60000",
      bottomBarTextColor: "#ffffff",
      ctaBarColor: "#e60000",
      ctaTextColor: "#ffffff",
      priceColor: "#fff200",
      accentColor: "#fff200",
      headlineFontPreset: "impact-korean-red",
      headlineFontWeight: 900,
      headlineLetterSpacing: -4,
      headlineLineHeight: 0.94,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 124,
      bodyFontSize: 58,
      highlightFontSize: 42,
      bottomBarFontSize: 46,
      ctaFontSize: 48,
    },
    zones: {
      body: "top-black-support-copy",
      headline: "top-red-impact-copy",
      price: "middle-red-price-bar",
      product: "large-main-image",
      cta: "bottom-red-cta",
    },
    copyLimits: foodTemplateCopyLimits["camping-popularity-impact"],
  },
  {
    id: "circle-focus-review",
    name: "원형포커스후기형",
    category: "범용/후기",
    templateGroup: "new-reference",
    description:
      "실사용 이미지 위에 원형 포커스 링을 얹고 하단에 후기형 카피를 크게 배치하는 UGC 리뷰형 템플릿입니다.",
    recommendedHookTypes: ["후기/리뷰형", "공감형", "문제제기형", "UGC형"],
    recommendedAppealPoints: ["실사용감", "문제해결", "공감", "후기"],
    style: {
      backgroundColor: "#ffffff",
      headlineColor: "#111111",
      bodyColor: "#111111",
      highlightBackground: "#ffffff",
      highlightTextColor: "#111111",
      bottomBarColor: "#ffffff",
      bottomBarTextColor: "#111111",
      ctaBarColor: "#e60000",
      ctaTextColor: "#ffffff",
      priceColor: "#e60000",
      accentColor: "#e60000",
      headlineFontPreset: "commerce-heavy-black",
      headlineFontWeight: 900,
      headlineLetterSpacing: -2,
      headlineLineHeight: 1.08,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 74,
      bodyFontSize: 36,
      highlightFontSize: 34,
      bottomBarFontSize: 30,
      ctaFontSize: 28,
    },
    zones: {
      product: "top-real-use-image",
      focus: "center-red-circle",
      headline: "bottom-review-copy",
      price: "small-bottom-badge",
    },
    copyLimits: foodTemplateCopyLimits["circle-focus-review"],
  },
  {
    id: "black-repeat-product",
    name: "블랙반복제품형",
    category: "범용/제품",
    templateGroup: "new-reference",
    description:
      "검정 배경 위에 제품 컷을 반복 배치하고 민트 정보바와 강한 헤드라인으로 구성하는 제품 강조형 템플릿입니다.",
    recommendedHookTypes: ["UGC형", "가격정당화형", "후기/리뷰형", "상황제안형"],
    recommendedAppealPoints: ["제품반복노출", "혜택", "기능", "가격"],
    style: {
      backgroundColor: "#050505",
      headlineColor: "#ffffff",
      bodyColor: "#ffffff",
      highlightBackground: "#18ead8",
      highlightTextColor: "#001111",
      bottomBarColor: "#18ead8",
      bottomBarTextColor: "#001111",
      ctaBarColor: "#18ead8",
      ctaTextColor: "#001111",
      priceColor: "#ff2b2b",
      accentColor: "#18ead8",
      headlineFontPreset: "ugc-bold-white",
      headlineFontWeight: 900,
      headlineLetterSpacing: -3,
      headlineLineHeight: 0.98,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 108,
      bodyFontSize: 48,
      highlightFontSize: 42,
      bottomBarFontSize: 38,
      ctaFontSize: 30,
    },
    zones: {
      body: "top-handwritten-copy",
      headline: "top-main-impact",
      product: "middle-repeated-products",
      highlight: "bottom-mint-info-bar",
    },
    copyLimits: foodTemplateCopyLimits["black-repeat-product"],
  },
  {
    id: "sports-benefit-chip",
    name: "스포츠성분칩형",
    category: "범용/기능",
    templateGroup: "new-reference",
    description:
      "어두운 배경, 좌측 굵은 헤드라인, 성분/혜택 pill 3개, 우측 제품 spotlight를 조합한 기능 소구형 템플릿입니다.",
    recommendedHookTypes: ["문제제기형", "상황제안형", "후기/리뷰형", "UGC형"],
    recommendedAppealPoints: ["성분", "효과", "기능", "실사용"],
    style: {
      backgroundColor: "#050b0f",
      headlineColor: "#ffffff",
      bodyColor: "#ffffff",
      highlightBackground: "#18e6c5",
      highlightTextColor: "#001111",
      bottomBarColor: "#ffffff",
      bottomBarTextColor: "#111111",
      ctaBarColor: "#18e6c5",
      ctaTextColor: "#001111",
      priceColor: "#18e6c5",
      accentColor: "#18e6c5",
      headlineFontPreset: "ugc-bold-white",
      headlineFontWeight: 900,
      headlineLetterSpacing: -3,
      headlineLineHeight: 1.05,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 76,
      bodyFontSize: 36,
      highlightFontSize: 36,
      bottomBarFontSize: 34,
      ctaFontSize: 32,
    },
    zones: {
      background: "dark-sports-scene",
      headline: "left-heavy-copy",
      product: "right-spotlight-product",
      highlight: "left-benefit-chips",
      cta: "bottom-left-small-cta",
    },
    copyLimits: foodTemplateCopyLimits["sports-benefit-chip"],
  },
  {
    id: "before-after-split-review",
    name: "전후분할후기형",
    category: "범용/후기",
    templateGroup: "new-reference",
    description:
      "좌측 실사용 이미지와 우측 정보 패널을 분할해 문제 해결/전후 비교/분위기형 후기를 보여주는 템플릿입니다.",
    recommendedHookTypes: ["문제제기형", "공감형", "후기/리뷰형", "상황제안형"],
    recommendedAppealPoints: ["문제해결", "전후비교", "공감", "제품효과"],
    style: {
      backgroundColor: "#ffffff",
      headlineColor: "#111111",
      bodyColor: "#111111",
      highlightBackground: "#ffffff",
      highlightTextColor: "#111111",
      bottomBarColor: "#ffffff",
      bottomBarTextColor: "#111111",
      ctaBarColor: "#00afa5",
      ctaTextColor: "#ffffff",
      priceColor: "#00afa5",
      accentColor: "#00afa5",
      headlineFontPreset: "commerce-heavy-black",
      headlineFontWeight: 900,
      headlineLetterSpacing: -2,
      headlineLineHeight: 1.08,
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 68,
      bodyFontSize: 34,
      highlightFontSize: 32,
      bottomBarFontSize: 30,
      ctaFontSize: 30,
    },
    zones: {
      before: "left-use-scene",
      panel: "right-white-info-panel",
      headline: "right-main-copy",
      product: "right-bottom-product",
      notes: "handwritten-support-copy",
    },
    copyLimits: foodTemplateCopyLimits["before-after-split-review"],
  },
];

const splitMeatDealTemplate = foodCategoryTemplates.find(
  (template) => template.id === "food-template-001"
);

if (splitMeatDealTemplate) {
  Object.assign(splitMeatDealTemplate, {
    name: "분할고기특가형 템플릿",
    category: "식품/선물",
    description:
      "여러 컷의 고기/상품 이미지를 분할 배치하고, 상단 헤드라인과 하단 상품명·기존가·배지·판매가를 강하게 보여주는 식품 특가형 템플릿입니다.",
    recommendedHookTypes: ["가격정당화형", "가격충격형", "긴급/한정형", "선물명분형"],
    recommendedAppealPoints: ["가성비", "대용량", "특가", "선물 명분"],
    typography: {
      headlineFontSize: 86,
      bodyFontSize: 36,
      highlightFontSize: 30,
      bottomBarFontSize: 36,
      ctaFontSize: 24,
    },
    style: {
      ...splitMeatDealTemplate.style,
      backgroundColor: "#111111",
      headlineColor: "#ffffff",
      bodyColor: "#ffffff",
      highlightBackground: "#ff1f1f",
      highlightTextColor: "#ffffff",
      bottomBarColor: "#111111",
      bottomBarTextColor: "#ffffff",
      priceColor: "#fff238",
      accentColor: "#fff238",
      headlineFontPreset: "impact-korean-red",
      headlineFontWeight: 900,
      headlineLetterSpacing: -3,
      headlineLineHeight: 0.98,
    },
    zones: {
      headline: "top-impact-headline",
      product: "middle-split-product-images-1-to-4",
      body: "bottom-left-product-name",
      bottom: "bottom-left-original-price",
      highlight: "bottom-left-red-special-badge",
      price: "bottom-right-sale-price",
      cta: "optional-hidden",
    },
    copyLimits: foodTemplateCopyLimits["food-template-001"],
  });
}

const commonSafeArea = { top: 28, right: 28, bottom: 28, left: 28 };

const referenceTemplateUpgrades: Record<string, Partial<BannerTemplateDefinition>> = {
  "camping-popularity-impact": {
    renderMode: "slot-engine",
    visualTone: "commerce-offer",
    palettePolicy: "accent-only",
    textStylePresetKey: "commerceOffer",
    variantPreference: { preferred: "short", fallbackOrder: ["medium", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        role: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 54,
        y: 42,
        width: 1092,
        height: 220,
        zIndex: 10,
        safePadding: 8,
        maxLines: 2,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 0,
        y: 276,
        width: 1200,
        height: 76,
        zIndex: 11,
        safePadding: 18,
        maxLines: 1,
        allowShrink: true,
        priority: 76,
      },
      {
        id: "product",
        type: "image",
        x: 90,
        y: 352,
        width: 1020,
        height: 548,
        zIndex: 7,
        priority: 98,
        imageFit: "transparent-product",
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 62,
        y: 914,
        width: 520,
        height: 62,
        zIndex: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 60,
      },
      {
        id: "price",
        type: "price",
        role: "price",
        x: 578,
        y: 902,
        width: 558,
        height: 92,
        zIndex: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 0,
        y: 1008,
        width: 1200,
        height: 80,
        zIndex: 14,
        safePadding: 16,
        maxLines: 1,
        allowShrink: true,
        priority: 72,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 0,
        y: 1088,
        width: 1200,
        height: 112,
        zIndex: 14,
        safePadding: 18,
        maxLines: 1,
        allowShrink: true,
        priority: 88,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
  "circle-focus-review": {
    renderMode: "slot-engine",
    visualTone: "testimonial-focus",
    palettePolicy: "accent-only",
    textStylePresetKey: "testimonialClean",
    variantPreference: { preferred: "medium", fallbackOrder: ["short", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        role: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "product",
        type: "image",
        x: 745,
        y: 390,
        width: 390,
        height: 460,
        zIndex: 8,
        priority: 96,
        imageFit: "transparent-product",
      },
      {
        id: "body",
        type: "text",
        role: "reviewQuote",
        x: 62,
        y: 748,
        width: 650,
        height: 112,
        zIndex: 11,
        maxLines: 2,
        allowShrink: true,
        priority: 66,
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 58,
        y: 866,
        width: 1084,
        height: 176,
        zIndex: 11,
        maxLines: 2,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 64,
        y: 1054,
        width: 440,
        height: 64,
        zIndex: 12,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 72,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 530,
        y: 1054,
        width: 606,
        height: 92,
        zIndex: 12,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
  "black-repeat-product": {
    renderMode: "slot-engine",
    visualTone: "product-repeat",
    palettePolicy: "protected-palette",
    textStylePresetKey: "productRepeatImpact",
    variantPreference: { preferred: "short", fallbackOrder: ["medium", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        role: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 60,
        y: 48,
        width: 1080,
        height: 76,
        zIndex: 11,
        maxLines: 1,
        allowShrink: true,
        priority: 58,
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 52,
        y: 132,
        width: 1096,
        height: 210,
        zIndex: 11,
        maxLines: 2,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "product1",
        type: "image",
        x: -55,
        y: 375,
        width: 310,
        height: 565,
        zIndex: 7,
        priority: 78,
        imageFit: "repeat-product",
        intentionalOverlapWith: ["product2"],
      },
      {
        id: "product2",
        type: "image",
        x: 185,
        y: 350,
        width: 330,
        height: 590,
        zIndex: 8,
        priority: 86,
        imageFit: "repeat-product",
        intentionalOverlapWith: ["product1", "product3"],
      },
      {
        id: "product3",
        type: "image",
        x: 435,
        y: 350,
        width: 350,
        height: 600,
        zIndex: 9,
        priority: 98,
        imageFit: "repeat-product",
        intentionalOverlapWith: ["product2", "product4"],
      },
      {
        id: "product4",
        type: "image",
        x: 705,
        y: 350,
        width: 330,
        height: 590,
        zIndex: 8,
        priority: 86,
        imageFit: "repeat-product",
        intentionalOverlapWith: ["product3", "product5"],
      },
      {
        id: "product5",
        type: "image",
        x: 965,
        y: 375,
        width: 310,
        height: 565,
        zIndex: 7,
        priority: 78,
        imageFit: "repeat-product",
        intentionalOverlapWith: ["product4"],
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 0,
        y: 952,
        width: 1200,
        height: 84,
        zIndex: 12,
        safePadding: 16,
        maxLines: 1,
        allowShrink: true,
        priority: 74,
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 0,
        y: 1036,
        width: 1200,
        height: 74,
        zIndex: 13,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 70,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 0,
        y: 1110,
        width: 1200,
        height: 90,
        zIndex: 13,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 84,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: false,
    maximumImageCount: 1,
    optimizationEnabled: true,
  },
  "sports-benefit-chip": {
    renderMode: "slot-engine",
    visualTone: "feature-proof",
    palettePolicy: "protected-palette",
    textStylePresetKey: "featureProof",
    variantPreference: { preferred: "medium", fallbackOrder: ["short", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        role: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 58,
        y: 70,
        width: 610,
        height: 308,
        zIndex: 10,
        maxLines: 4,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 66,
        y: 410,
        width: 535,
        height: 100,
        zIndex: 10,
        maxLines: 2,
        allowShrink: true,
        priority: 60,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 66,
        y: 544,
        width: 510,
        height: 70,
        zIndex: 11,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 76,
      },
      {
        id: "product",
        type: "image",
        x: 610,
        y: 250,
        width: 560,
        height: 704,
        zIndex: 8,
        priority: 98,
        imageFit: "transparent-product",
        intentionalOverlapWith: ["headline", "body", "highlight"],
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 58,
        y: 960,
        width: 1084,
        height: 78,
        zIndex: 12,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 68,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 58,
        y: 1060,
        width: 1084,
        height: 94,
        zIndex: 12,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
  "before-after-split-review": {
    renderMode: "slot-engine",
    visualTone: "lifestyle-split",
    palettePolicy: "accent-only",
    textStylePresetKey: "lifestyleSplit",
    variantPreference: { preferred: "medium", fallbackOrder: ["short", "long"] },
    slots: [
      {
        id: "scene",
        type: "image",
        role: "scene",
        x: 0,
        y: 0,
        width: 585,
        height: 1200,
        zIndex: 2,
        priority: 90,
        imageFit: "background-image",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 632,
        y: 64,
        width: 510,
        height: 284,
        zIndex: 10,
        maxLines: 4,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 640,
        y: 372,
        width: 486,
        height: 116,
        zIndex: 10,
        maxLines: 2,
        allowShrink: true,
        priority: 62,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 640,
        y: 520,
        width: 470,
        height: 66,
        zIndex: 11,
        safePadding: 11,
        maxLines: 1,
        allowShrink: true,
        priority: 74,
      },
      {
        id: "product",
        type: "image",
        x: 680,
        y: 600,
        width: 420,
        height: 392,
        zIndex: 8,
        priority: 98,
        imageFit: "transparent-product",
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 626,
        y: 1004,
        width: 516,
        height: 66,
        zIndex: 11,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 68,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 626,
        y: 1082,
        width: 516,
        height: 86,
        zIndex: 11,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
};

for (const template of foodCategoryTemplates) {
  const upgrade = referenceTemplateUpgrades[template.id];
  if (upgrade) Object.assign(template, upgrade);
}

const optimizedCopyLimits: TemplateCopyLimits = {
  headline: {
    maxChars: 30,
    maxLines: 3,
    minFontSize: 38,
    maxFontSize: 88,
    overflowStrategy: "shrink-wrap-ellipsis",
  },
  bodyCopy: {
    maxChars: 48,
    maxLines: 3,
    minFontSize: 22,
    maxFontSize: 34,
    overflowStrategy: "shrink-wrap-ellipsis",
  },
  highlightCopy: {
    maxChars: 22,
    maxLines: 2,
    minFontSize: 20,
    maxFontSize: 32,
    overflowStrategy: "shrink-wrap-ellipsis",
  },
  bottomBarCopy: {
    maxChars: 34,
    maxLines: 2,
    minFontSize: 20,
    maxFontSize: 32,
    overflowStrategy: "shrink-wrap-ellipsis",
  },
  cta: {
    maxChars: 12,
    maxLines: 1,
    minFontSize: 20,
    maxFontSize: 31,
    overflowStrategy: "shrink-ellipsis",
  },
  price: {
    maxChars: 14,
    maxLines: 1,
    minFontSize: 38,
    maxFontSize: 78,
    overflowStrategy: "shrink-ellipsis",
  },
};

export const optimizedCategoryTemplates: BannerTemplateDefinition[] = [
  {
    id: "auto-meat-impact-001",
    name: "자동 최적화 · 고기 특가 임팩트",
    category: "식품/선물",
    templateGroup: "optimized-food",
    description: "실사 상품을 크게 유지하면서 헤드라인, 가격, 혜택의 우선순위를 자동 조정합니다.",
    recommendedHookTypes: ["가격충격형", "가격정당화형", "긴급/한정형"],
    recommendedAppealPoints: ["가격", "품질", "구성", "즉시혜택"],
    style: {
      backgroundColor: "#130d0a",
      surfaceColor: "#fffdf7",
      accentColor: "#fff238",
      priceColor: "#ff2d24",
      highlightBackground: "#fff238",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 88,
      bodyFontSize: 31,
      highlightFontSize: 28,
      bottomBarFontSize: 30,
      ctaFontSize: 29,
    },
    zones: {
      product: "full-bleed",
      headline: "top-overlay",
      offer: "lower-left",
      cta: "bottom-bars",
    },
    copyLimits: optimizedCopyLimits,
    renderMode: "slot-engine",
    visualTone: "meat-impact",
    palettePolicy: "protected-palette",
    textStylePresetKey: "foodImpact",
    variantPreference: { preferred: "medium", fallbackOrder: ["short", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 62,
        y: 62,
        width: 1076,
        height: 238,
        zIndex: 10,
        safePadding: 8,
        maxLines: 2,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 70,
        y: 322,
        width: 665,
        height: 106,
        zIndex: 10,
        maxLines: 2,
        allowShrink: true,
        priority: 65,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 70,
        y: 452,
        width: 500,
        height: 72,
        zIndex: 11,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 74,
      },
      {
        id: "product",
        type: "image",
        x: 625,
        y: 270,
        width: 540,
        height: 690,
        zIndex: 8,
        priority: 95,
        imageFit: "transparent-product",
        intentionalOverlapWith: ["headline", "body", "highlight"],
        requiresDistinctImage: true,
      },
      {
        id: "originalPrice",
        type: "price",
        role: "originalPrice",
        x: 72,
        y: 760,
        width: 360,
        height: 58,
        zIndex: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 55,
      },
      {
        id: "badge",
        type: "badge",
        role: "productBadge",
        x: 72,
        y: 835,
        width: 142,
        height: 66,
        zIndex: 12,
        safePadding: 10,
        maxLines: 1,
        priority: 55,
      },
      {
        id: "price",
        type: "price",
        role: "price",
        x: 234,
        y: 812,
        width: 485,
        height: 112,
        zIndex: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 0,
        y: 1016,
        width: 1200,
        height: 84,
        zIndex: 15,
        safePadding: 18,
        maxLines: 1,
        allowShrink: true,
        priority: 70,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 0,
        y: 1100,
        width: 1200,
        height: 100,
        zIndex: 15,
        safePadding: 18,
        maxLines: 1,
        allowShrink: true,
        priority: 88,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
  {
    id: "auto-produce-market-001",
    name: "자동 최적화 · 산지 직송 마켓",
    category: "식품/농산물",
    templateGroup: "optimized-food",
    description: "농산물의 신선도와 산지 이미지를 밝은 편집형 레이아웃으로 보여줍니다.",
    recommendedHookTypes: ["상황제안형", "신뢰형", "가격정당화형"],
    recommendedAppealPoints: ["신선도", "산지", "제철", "구성"],
    style: {
      backgroundColor: "#fffaf1",
      surfaceColor: "#ffffff",
      accentColor: "#4f8b45",
      priceColor: "#d83b32",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 82,
      bodyFontSize: 30,
      highlightFontSize: 27,
      bottomBarFontSize: 29,
      ctaFontSize: 28,
    },
    zones: {
      headline: "upper-left",
      product: "right-hero",
      benefits: "left-stack",
      price: "lower-left",
    },
    copyLimits: optimizedCopyLimits,
    renderMode: "slot-engine",
    visualTone: "produce-editorial",
    palettePolicy: "accent-only",
    textStylePresetKey: "foodProduceEditorial",
    variantPreference: { preferred: "medium", fallbackOrder: ["long", "short"] },
    slots: [
      {
        id: "product",
        type: "image",
        x: 555,
        y: 42,
        width: 605,
        height: 905,
        zIndex: 3,
        priority: 95,
        imageFit: "cover",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 62,
        y: 70,
        width: 500,
        height: 270,
        zIndex: 8,
        safePadding: 6,
        maxLines: 3,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 64,
        y: 370,
        width: 460,
        height: 150,
        zIndex: 8,
        maxLines: 3,
        allowShrink: true,
        priority: 62,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 64,
        y: 550,
        width: 420,
        height: 72,
        zIndex: 8,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 72,
      },
      {
        id: "originalPrice",
        type: "price",
        role: "originalPrice",
        x: 64,
        y: 704,
        width: 300,
        height: 52,
        zIndex: 8,
        maxLines: 1,
        allowShrink: true,
        priority: 50,
      },
      {
        id: "price",
        type: "price",
        role: "price",
        x: 64,
        y: 770,
        width: 470,
        height: 106,
        zIndex: 8,
        maxLines: 1,
        allowShrink: true,
        priority: 98,
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 46,
        y: 956,
        width: 1108,
        height: 82,
        zIndex: 10,
        safePadding: 16,
        maxLines: 1,
        allowShrink: true,
        priority: 70,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 46,
        y: 1060,
        width: 1108,
        height: 96,
        zIndex: 10,
        safePadding: 16,
        maxLines: 1,
        allowShrink: true,
        priority: 85,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: false,
    maximumImageCount: 1,
    optimizationEnabled: true,
  },
  {
    id: "auto-beauty-editorial-001",
    name: "자동 최적화 · 뷰티 에디토리얼",
    category: "뷰티",
    templateGroup: "optimized-beauty",
    description:
      "제품 패키지를 훼손하지 않고 여백, 세리프 타이포, 성분 포인트로 고급스럽게 구성합니다.",
    recommendedHookTypes: ["문제제기형", "상황제안형", "후기/리뷰형"],
    recommendedAppealPoints: ["사용감", "성분", "결과", "감성"],
    style: {
      backgroundColor: "#f8f2f0",
      surfaceColor: "#ffffff",
      accentColor: "#b9677a",
      priceColor: "#9f4358",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 72,
      bodyFontSize: 29,
      highlightFontSize: 26,
      bottomBarFontSize: 28,
      ctaFontSize: 28,
    },
    zones: { editorial: "left-copy", product: "right-still-life", details: "lower-band" },
    copyLimits: optimizedCopyLimits,
    renderMode: "slot-engine",
    visualTone: "beauty-editorial",
    palettePolicy: "full-auto",
    textStylePresetKey: "beautyEditorial",
    variantPreference: { preferred: "long", fallbackOrder: ["medium", "short"] },
    slots: [
      {
        id: "product",
        type: "image",
        x: 570,
        y: 70,
        width: 560,
        height: 805,
        zIndex: 3,
        priority: 98,
        imageFit: "contain",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 66,
        y: 94,
        width: 500,
        height: 300,
        zIndex: 8,
        maxLines: 3,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 70,
        y: 430,
        width: 455,
        height: 170,
        zIndex: 8,
        maxLines: 3,
        allowShrink: true,
        priority: 62,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 70,
        y: 645,
        width: 410,
        height: 66,
        zIndex: 8,
        safePadding: 10,
        maxLines: 1,
        allowShrink: true,
        priority: 70,
      },
      {
        id: "price",
        type: "price",
        role: "price",
        x: 70,
        y: 758,
        width: 430,
        height: 92,
        zIndex: 8,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 70,
        y: 912,
        width: 1060,
        height: 82,
        zIndex: 10,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 68,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 70,
        y: 1026,
        width: 1060,
        height: 98,
        zIndex: 10,
        safePadding: 16,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: false,
    maximumImageCount: 1,
    optimizationEnabled: true,
  },
  {
    id: "auto-beauty-proof-002",
    name: "자동 최적화 · 성분 근거 카드",
    category: "뷰티/바디",
    templateGroup: "optimized-beauty",
    description: "실사용 장면과 제품 컷, 핵심 효능을 정보 카드 구조로 정리합니다.",
    recommendedHookTypes: ["문제제기형", "전문가/권위형", "후기/리뷰형"],
    recommendedAppealPoints: ["문제해결", "성분", "근거", "사용후기"],
    style: {
      backgroundColor: "#f4f7f7",
      surfaceColor: "#ffffff",
      accentColor: "#18a894",
      priceColor: "#127e70",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 76,
      bodyFontSize: 28,
      highlightFontSize: 25,
      bottomBarFontSize: 28,
      ctaFontSize: 28,
    },
    zones: { useScene: "left-photo", information: "right-panel", product: "right-product" },
    copyLimits: optimizedCopyLimits,
    renderMode: "slot-engine",
    visualTone: "beauty-clinical",
    palettePolicy: "accent-only",
    textStylePresetKey: "beautyClinical",
    variantPreference: { preferred: "medium", fallbackOrder: ["short", "long"] },
    slots: [
      {
        id: "scene",
        type: "image",
        x: 0,
        y: 0,
        width: 585,
        height: 1200,
        zIndex: 2,
        priority: 82,
        imageFit: "cover",
      },
      {
        id: "product",
        type: "image",
        x: 690,
        y: 535,
        width: 400,
        height: 395,
        zIndex: 6,
        priority: 96,
        imageFit: "contain",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 635,
        y: 76,
        width: 500,
        height: 260,
        zIndex: 8,
        maxLines: 3,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 640,
        y: 365,
        width: 475,
        height: 126,
        zIndex: 8,
        maxLines: 3,
        allowShrink: true,
        priority: 60,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 640,
        y: 958,
        width: 475,
        height: 66,
        zIndex: 9,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 72,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 640,
        y: 1050,
        width: 475,
        height: 92,
        zIndex: 9,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
  {
    id: "auto-body-solution-001",
    name: "자동 최적화 · 바디 문제해결",
    category: "뷰티/바디",
    templateGroup: "optimized-beauty",
    description: "어두운 실사용 배경 위에 제품과 해결 포인트를 민트 액센트로 명확히 분리합니다.",
    recommendedHookTypes: ["문제제기형", "반전/궁금증형", "후기/리뷰형"],
    recommendedAppealPoints: ["불편해결", "효과", "사회적 증거", "즉시혜택"],
    style: {
      backgroundColor: "#0d1716",
      surfaceColor: "#152624",
      accentColor: "#20e8ca",
      priceColor: "#20e8ca",
      fontFamily: baseFoodFont,
    },
    typography: {
      headlineFontSize: 78,
      bodyFontSize: 29,
      highlightFontSize: 26,
      bottomBarFontSize: 28,
      ctaFontSize: 28,
    },
    zones: {
      scene: "full-bleed",
      message: "left-overlay",
      product: "right-focus",
      actions: "bottom",
    },
    copyLimits: optimizedCopyLimits,
    renderMode: "slot-engine",
    visualTone: "body-proof",
    palettePolicy: "protected-palette",
    textStylePresetKey: "bodyProof",
    variantPreference: { preferred: "short", fallbackOrder: ["medium", "long"] },
    slots: [
      {
        id: "background",
        type: "image",
        x: 0,
        y: 0,
        width: 1200,
        height: 1200,
        zIndex: 1,
        priority: 100,
        imageFit: "background-image",
      },
      {
        id: "headline",
        type: "text",
        role: "headline",
        x: 62,
        y: 76,
        width: 625,
        height: 300,
        zIndex: 9,
        maxLines: 3,
        allowShrink: true,
        priority: 100,
      },
      {
        id: "body",
        type: "text",
        role: "bodyCopy",
        x: 66,
        y: 405,
        width: 560,
        height: 135,
        zIndex: 9,
        maxLines: 3,
        allowShrink: true,
        priority: 61,
      },
      {
        id: "highlight",
        type: "chip",
        role: "highlight",
        x: 66,
        y: 575,
        width: 500,
        height: 68,
        zIndex: 9,
        safePadding: 12,
        maxLines: 1,
        allowShrink: true,
        priority: 72,
      },
      {
        id: "product",
        type: "image",
        x: 630,
        y: 250,
        width: 520,
        height: 690,
        zIndex: 7,
        priority: 98,
        imageFit: "contain",
        intentionalOverlapWith: ["headline", "body", "highlight"],
      },
      {
        id: "bottomBar",
        type: "text",
        role: "bottomBar",
        x: 58,
        y: 958,
        width: 1084,
        height: 80,
        zIndex: 10,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 69,
      },
      {
        id: "cta",
        type: "cta",
        role: "cta",
        x: 58,
        y: 1060,
        width: 1084,
        height: 94,
        zIndex: 10,
        safePadding: 14,
        maxLines: 1,
        allowShrink: true,
        priority: 86,
      },
    ],
    safeArea: commonSafeArea,
    supportsMultipleImages: true,
    maximumImageCount: 2,
    optimizationEnabled: true,
  },
];

export const qualityFoodTemplates = optimizedCategoryTemplates.filter(
  (template) => template.templateGroup === "optimized-food"
);

export const beautyCategoryTemplates = optimizedCategoryTemplates.filter(
  (template) => template.templateGroup === "optimized-beauty"
);

export const healthCategoryTemplates = [
  ...optimizedCategoryTemplates.filter((template) =>
    ["auto-beauty-proof-002", "auto-body-solution-001"].includes(template.id)
  ),
  ...foodCategoryTemplates.filter((template) =>
    [
      "circle-focus-review",
      "black-repeat-product",
      "sports-benefit-chip",
      "before-after-split-review",
    ].includes(template.id)
  ),
];

export const templatesById = new Map(
  [...foodCategoryTemplates, ...optimizedCategoryTemplates].map((template) => [
    template.id,
    template,
  ])
);
export const foodCategoryTemplateIds = [
  ...foodCategoryTemplates,
  ...optimizedCategoryTemplates,
].map((template) => template.id);

export const foodImpactHeroTemplate = {
  id: "food-impact-hero-001",
  style: {
    backgroundColor: "#ffffff",
    headlineColor: "#ff1f1f",
    headlineFontPreset: "impact-korean-red" as HeadlineFontPresetId,
    headlineFontFamily: headlineFontPresets["impact-korean-red"].fontFamily,
    headlineFontSize: 108,
    headlineFontWeight: 900,
    headlineLetterSpacing: -4,
    headlineLineHeight: 0.95,
    headlineTextStroke: false,
    headlineTextStrokeColor: "#111111",
    headlineTextStrokeWidth: 0,
    headlineShadow: true,
    headlineShadowColor: "rgba(255, 31, 31, 0.18)",
    headlineShadowBlur: 0,
    headlineShadowOffsetX: 1,
    headlineShadowOffsetY: 2,
    bodyColor: "#111111",
    highlightBackground: "#fff56a",
    highlightTextColor: "#111111",
    bottomBarColor: "#ff1f1f",
    bottomBarTextColor: "#ffffff",
    ctaBarColor: "#e58585",
    ctaTextColor: "#ffffff",
    priceColor: "#ff1f1f",
    accentColor: "#fff9a8",
    fontFamily: 'Pretendard, "Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", sans-serif',
  },
  typography: {
    headlineFontSize: 108,
    bodyFontSize: 38,
    highlightFontSize: 32,
    bottomBarFontSize: 37,
    ctaFontSize: 34,
    headlineLineHeight: 0.95,
    bodyLineHeight: 1.22,
    highlightLineHeight: 1.14,
    letterSpacing: -4,
  },
  copyLimits: foodTemplateCopyLimits["food-impact-hero-001"],
};

export type FoodImpactHeroTemplate = typeof foodImpactHeroTemplate;
